[build]
  command = "pip install -r requirements.txt && cd mvskoke-demo-site && npm run build --prod"
  publish = "dist/mvskoke-demo-site"

[dev]
  command = "uvicorn app:app --reload"
  port = 8000
  targetPort = 8000
